version: "3"
services:
  app:
    build:
      context: app
      dockerfile: ../Dockerfile.dev
    command: bash -c 'npm i; npm run dev'
    ports:
      - "3000:3000"
    volumes:
      - "./app:/app"
